### ISSUE TITLE
another library's benchmark

### ISSUE THREAD

**Issue by jtarchie** [influxdata/go-syslog#10]
I tried out your [benchmarks with my library](https://github.com/jtarchie/syslog/issues/1).

Some notes:
* Didn't originally support multiple sd elements, so that was added for these benchmarks. Wish the RFC read better on this.
* Don't support all the error messages you have here. An error is returned for malformed syslog format, but not what caused the error.
* No validation is done on the uniqueness of sd id. I'm using a different data structure as sd elements can have the key defined multiple times.
* Don't use pointers. Just the `string` conversion from the `[]byte`.

**Comment by leodido** [comment]
Hi @jtarchie congrats for your library. :)

Would be interesting to look at the results of this library on your machine.
Also would be very interesting to adapt the test cases of this package and run them on your library.

Notice that priority values have to be within `[1,191]` or be `0` (ie., `002` is not a valid priority value) to be valid, since from them are computed the facility and the severity values as the RFC mandates.

Clearly there are a bunch of features of this library, namely:

- the precise error management part
- the UTF-8 matching for the message part 
- the UTF-8 matching for the sd param values
- the escaping/unescaping thing of `"`, `]`, `\` within sd param values
- the best effort mode support
- duplicated sd id matching
- the usage of `time.Parse` to parse timestamps 

that all slightly slow down a bit this library.

These were chosen due to the trade-off between speed, correctness (RFC5424-compliance) and library features.

**Comment by jtarchie** [comment]
I'll take a crack at the test cases here, too.

I don't know how I feel about the _best effort_ though. I feel that can be anti-functionality. What do you you use it for?

**Comment by leodido** [comment]
Ideas you give me (and I thank you!) are:

- [x] Try to match `any` and validate UTF-8 during the set of message part (idem for the sd param value)
   > Done. It fasten by 10-16% the match of inputs not containing UTF-8. At the same time it slows down the match of long syslog or syslog containing UTF-8 sequences from 20% to 60% (since we need to use `utf8.Valid` to check the validity of string and in the besteffort mode we need to iterate on the string to extract the valid UTF-8 part) ... Leaving as is for now.

- [x] Try to match `any` and validate UTF-8 during the set of sd param value part

    > As above.


- [x] Try to match prival in the simple way and then check it is in the range [1,191] or 0 during the set

    > Done. It slows down the average case of 12% (increasing performance by 3-5% in early error cases)

**Comment by leodido** [comment]
The best effort thing is useful when you want to extract (and store) a syslog message also if it was not completely compliant to the rules.

Since from a lot of years a lot of software do syslog messages in a "free" way it is very common that some syslog messages are only partially compliant to that RFC5424.

With the best effort mode we can save it if it is minimally valid - ie., until the point that breaks the rules it is correct and contains almost a valid priority value and a valid version (which are the only two fields that cannot have nil values by RFC).

**Comment by jtarchie** [comment]
I do have a best effort then as I allow any prival range. 😄

**Comment by leodido** [comment]
Best effort does not allow any priority values, only valid ones :stuck_out_tongue_closed_eyes:

**Comment by leodido** [comment]
I have tested ideas from your impl., namely [these](https://github.com/influxdata/go-syslog/issues/10#issuecomment-385183819).

Closing for now.
